# try-catch와 에러핸들링

### 1. 개요
컴퓨터 프로그램은 언제 어떻게 발생할지 모르는 예외 상황에 대처하기 위한 대비가 잘 되어 있어야 한다. 프로그램이 예상과는 다른 결과(실수, 예상치 못한 사용자 입력, 잘못된 서버 응답등의 수천만가지 이유)를 마주치게 될 때, 또는 에러상황에 직면해 있을 때 등의 상황에 대처하기 위한 코딩이 되어 있어야 좋은 프로그램이라고 할 수 있다. 따라서 웹프로그래밍에서도 예외처리를 사용한다.

### 2. 간단한 사용법

딱 간단히 살펴보면 다음과 같은 블럭들을 가진다고 보면 된다. 
```js
try {

	  alert('일단 이 구문을 실행한다');
	  
  } catch(err) { // 위 try 블록에서 예외(에러)가 발생 시 이 블록을 실행한다
		  
	  alert('위 try 블록에서 에러 발생 시 이 블록을 실행한다');
      console.log(err.name);
		  
  } finally {
      alert('예외(에러)가 발생 여부에 상관없이 이 블록을 실행한다.');
}
```
이를 활용해서 JSON으로 인코딩된 값을 읽을 수 있도록 해주는 JSON.parse(str)메서드에서 try-catch문을 사용한다.
여기서 에러처리를 하는 이유는 다양하겠지만, 잘못된 형식의 json이 들어온 경우 JSON.parse는 에러를 만들기 때문에 스크립트가 죽는다. 예외처리를 통해 이를 대비할 수 있다.

+)JSON.parse(str)메서드 -> 주로 서버/네트워크에서 전달받은 데이터를 디코딩하는데 사용 : 전달받은 데이터에 JSON.parse를 호출하는 식으로 사용

```js
let json = {
    "name":"john", 
    "age":30, 
    "bad json"
}

try{
    let user = JSON.parse(json);

    alert(user.name);
    alert(user.age);
}catch(e){
    alert('데이터에 에러가 있어 재요청을 시도합니다.');
    alert(e.name);
    alert(e.message);
}



